#!/usr/bin/env python3
"""Build script: generate a self-contained WASM notebook and export to dist/.

What it does
------------
1.  Reads every Python module in ``src/vault/``.
2.  Reads every Markdown note from ``vault/`` and ``skills/``.
3.  Reads every TOML plugin descriptor from ``plugins/``.
4.  Generates ``notebooks/vault_app_wasm.py`` — a standalone Marimo notebook
    with a bootstrap cell that writes all vault source + data to the Pyodide
    virtual filesystem (MEMFS) before anything else runs.
5.  Runs ``marimo export html-wasm`` on the generated notebook, writing the
    static site to ``dist/``.

Usage::

    uv run python scripts/build_wasm.py           # generate + export
    uv run python scripts/build_wasm.py --gen-only  # only generate notebook
"""

from __future__ import annotations

import argparse
import subprocess
import sys
import textwrap
from pathlib import Path

ROOT = Path(__file__).parent.parent
SRC_VAULT = ROOT / "src" / "vault"
VAULT_NOTES_DIR = ROOT / "vault"
SKILLS_DIR = ROOT / "skills"
PLUGINS_DIR = ROOT / "plugins"
DIST_DIR = ROOT / "dist"
WASM_NOTEBOOK = ROOT / "notebooks" / "vault_app_wasm.py"
SOURCE_NOTEBOOK = ROOT / "notebooks" / "vault_app.py"


# ---------------------------------------------------------------------------
# File readers
# ---------------------------------------------------------------------------


def read_vault_modules() -> dict[str, str]:
    """Read every .py file under src/vault/ (excluding WASM-specific helpers)."""
    result: dict[str, str] = {}
    for path in sorted(SRC_VAULT.rglob("*.py")):
        rel = str(path.relative_to(SRC_VAULT))
        # Skip any previously-generated helpers
        if "_wasm" in rel:
            continue
        result[rel] = path.read_text(encoding="utf-8")
    return result


def read_md_dir(directory: Path) -> dict[str, str]:
    """slug → content for all .md files in *directory*."""
    result: dict[str, str] = {}
    if directory.exists():
        for path in sorted(directory.glob("**/*.md")):
            result[path.stem] = path.read_text(encoding="utf-8")
    return result


def read_toml_dir(directory: Path) -> dict[str, str]:
    """stem → content for all .toml files in *directory*."""
    result: dict[str, str] = {}
    if directory.exists():
        for path in sorted(directory.glob("*.toml")):
            result[path.stem] = path.read_text(encoding="utf-8")
    return result


# ---------------------------------------------------------------------------
# Notebook cell extraction
# ---------------------------------------------------------------------------


def extract_cells_after_setup(source: str) -> str:
    """Return every @app.cell block that appears *after* the _setup cell."""
    lines = source.splitlines(keepends=True)
    # Find line index of the second @app.cell (the first is _setup in our template)
    cell_starts = [i for i, ln in enumerate(lines) if ln.strip() == "@app.cell"]
    # Skip cells 0 (_wasm_init, injected) and 1 (_setup, replaced)
    # In source notebook there is no _wasm_init, so we skip cell 0 (_setup)
    if len(cell_starts) < 2:
        return ""
    # Everything from the second @app.cell onward (excluding the trailing
    # `if __name__ == "__main__":` block)
    remainder_lines = lines[cell_starts[1] :]
    # Drop the if-main guard at the end
    cutoff = len(remainder_lines)
    for i, ln in enumerate(remainder_lines):
        if ln.startswith('if __name__ == "__main__"'):
            cutoff = i
            break
    return "".join(remainder_lines[:cutoff])


# ---------------------------------------------------------------------------
# Notebook generator
# ---------------------------------------------------------------------------

_WASM_INIT_CELL = '''\
@app.cell
def _wasm_init():
    """
    WASM bootstrap: write vault package + data to the Pyodide virtual filesystem.

    AUTO-GENERATED by scripts/build_wasm.py — do not edit manually.
    """
    import sys
    from pathlib import Path

    _HOME = Path("/home/pyodide")

    # ── Vault Python package ──────────────────────────────────────────────
    _VAULT_MODULES: dict[str, str] = {vault_modules!r}

    _vault_pkg = _HOME / "vault"
    _vault_pkg.mkdir(parents=True, exist_ok=True)
    for _rel, _code in _VAULT_MODULES.items():
        _dest = _vault_pkg / _rel
        _dest.parent.mkdir(parents=True, exist_ok=True)
        _dest.write_text(_code, encoding="utf-8")

    if str(_HOME) not in sys.path:
        sys.path.insert(0, str(_HOME))

    # ── Vault notes ───────────────────────────────────────────────────────
    _VAULT_NOTES: dict[str, str] = {vault_notes!r}

    _vault_dir = _HOME / "vault_notes"
    _vault_dir.mkdir(exist_ok=True)
    for _slug, _md in _VAULT_NOTES.items():
        (_vault_dir / f"{{_slug}}.md").write_text(_md, encoding="utf-8")

    # ── Skill files ───────────────────────────────────────────────────────
    _SKILL_FILES: dict[str, str] = {skill_files!r}

    _skills_dir = _HOME / "vault_skills"
    _skills_dir.mkdir(exist_ok=True)
    for _slug, _md in _SKILL_FILES.items():
        (_skills_dir / f"{{_slug}}.md").write_text(_md, encoding="utf-8")

    # ── Plugin TOML descriptors ───────────────────────────────────────────
    _PLUGIN_TOML: dict[str, str] = {plugin_toml!r}

    _plugins_dir = _HOME / "vault_plugins"
    _plugins_dir.mkdir(exist_ok=True)
    for _name, _toml in _PLUGIN_TOML.items():
        (_plugins_dir / f"{{_name}}.toml").write_text(_toml, encoding="utf-8")

    return _vault_dir, _skills_dir, _plugins_dir

'''

_SETUP_CELL = '''\
@app.cell
def _setup(_wasm_init):
    """Bootstrap vault index, plugins, and sub-systems (WASM-adapted)."""
    _wasm_vault_dir, _wasm_skills_dir, _wasm_plugins_dir = _wasm_init

    from vault.db import VaultDB
    from vault.index import VaultIndex
    from vault.plugin import fire_hook, load_all_plugins
    from vault.skills import SkillIndex
    from vault.todos import scan_todos

    _index = VaultIndex(_wasm_vault_dir)
    _index.build()

    _plugins = load_all_plugins(_wasm_plugins_dir)
    fire_hook(_plugins, "on_load", index=_index)

    _skill_index = SkillIndex(_wasm_skills_dir)
    _skill_index.build()

    _todo_index = scan_todos(_index)
    _vault_db = VaultDB(_index)
    # Keep _VAULT_DIR name so downstream cells that reference it work unchanged
    _VAULT_DIR = _wasm_vault_dir

    return (
        _index,
        _plugins,
        _skill_index,
        _todo_index,
        _vault_db,
        _VAULT_DIR,
        fire_hook,
    )

'''

_NOTEBOOK_HEADER = '''\
import marimo

__generated_with = "0.13.10"
app = marimo.App(width="full", app_title="Marimo-Obsessed")

# AUTO-GENERATED by scripts/build_wasm.py — do not edit.
# Source: notebooks/vault_app.py


'''

_NOTEBOOK_FOOTER = '''\

if __name__ == "__main__":
    app.run()
'''


def generate_wasm_notebook(
    vault_modules: dict[str, str],
    vault_notes: dict[str, str],
    skill_files: dict[str, str],
    plugin_toml: dict[str, str],
    remaining_cells: str,
) -> str:
    """Assemble the complete WASM notebook source."""
    wasm_init = _WASM_INIT_CELL.format(
        vault_modules=vault_modules,
        vault_notes=vault_notes,
        skill_files=skill_files,
        plugin_toml=plugin_toml,
    )
    return _NOTEBOOK_HEADER + wasm_init + _SETUP_CELL + remaining_cells + _NOTEBOOK_FOOTER


# ---------------------------------------------------------------------------
# Export runner
# ---------------------------------------------------------------------------


def run_export() -> None:
    DIST_DIR.mkdir(exist_ok=True)
    cmd = [
        sys.executable, "-m", "marimo", "export", "html-wasm",
        str(WASM_NOTEBOOK),
        "-o", str(DIST_DIR),
        "--mode", "run",
        "--no-show-code",
    ]
    print(f"Running: {' '.join(cmd)}")
    subprocess.run(cmd, check=True, cwd=str(ROOT))
    print(f"\n✓ Static site written to {DIST_DIR}/")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--gen-only", action="store_true",
        help="Only generate vault_app_wasm.py, skip marimo export"
    )
    args = parser.parse_args()

    print("Reading vault source files …")
    vault_modules = read_vault_modules()
    print(f"  {len(vault_modules)} Python modules")

    print("Reading vault notes …")
    vault_notes = read_md_dir(VAULT_NOTES_DIR)
    print(f"  {len(vault_notes)} notes")

    print("Reading skill files …")
    skill_files = read_md_dir(SKILLS_DIR)
    print(f"  {len(skill_files)} skills")

    print("Reading plugin descriptors …")
    plugin_toml = read_toml_dir(PLUGINS_DIR)
    print(f"  {len(plugin_toml)} plugins")

    print("Extracting cells from vault_app.py …")
    source_nb = SOURCE_NOTEBOOK.read_text(encoding="utf-8")
    remaining = extract_cells_after_setup(source_nb)

    print("Generating vault_app_wasm.py …")
    notebook_src = generate_wasm_notebook(
        vault_modules, vault_notes, skill_files, plugin_toml, remaining
    )
    WASM_NOTEBOOK.write_text(notebook_src, encoding="utf-8")
    print(f"  Written {WASM_NOTEBOOK} ({len(notebook_src):,} bytes)")

    if args.gen_only:
        print("\nDone (--gen-only; skipped marimo export).")
        return

    print("\nRunning marimo export html-wasm …")
    run_export()


if __name__ == "__main__":
    main()
